### ISSUE TITLE
Face ID Broken, 

### ISSUE THREAD

**Issue by EchoSkill** [udevsharold/perseus#9]
Hi!, I want to work on your source code, to add an option to use this tweak without face id, I broke my face id sensor :(, I already tried but I need to know if is posible you help me with your these config.. I have another config and its more complicated,, or maybe if you can add this option you can help me too

**Comment by udevsharold** [comment]
I believe there was one user said they broke the face id (partially, I'm not sure since the mask detection still works) after screen replacement, I compiled the deb without using faceid for them, might or might not works for you.

https://github.com/udevsharold/repo/blob/gh-pages/debug_debs/com.udevs.perseus_1.2.3%7Ex2_iphoneos-arm.deb

**Comment by EchoSkill** [comment]
I tried it, but it doesn't work for me, that version still requires face ID and mine is no longer configured, so what I want to do is cancel the faceID requirement, and have it unlocked only when the Watch is Nearby

**Comment by EchoSkill** [comment]
Works!!! Thank you so much boss, that’s exactly what I was searching!!🫶🏻
